//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entitiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CVEntities : DbContext
    {
        public DB_CVEntities()
            : base("name=DB_CVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblDeneyimler> tblDeneyimler { get; set; }
        public virtual DbSet<tblEgitimler> tblEgitimler { get; set; }
        public virtual DbSet<tblHakkında> tblHakkında { get; set; }
        public virtual DbSet<tblIletisim> tblIletisim { get; set; }
        public virtual DbSet<tblSertifikalar> tblSertifikalar { get; set; }
        public virtual DbSet<tblYetenekler> tblYetenekler { get; set; }
        public virtual DbSet<tblHobiler> tblHobiler { get; set; }
    }
}
